---
- hosts: all
  gather_facts: true
  tasks:
    - set_fact:
        var1: "{{ var2 }}"
    - debug:
        msg: "This Updates the workinfo and the token is {{ Token }}"
    - debug:
        msg: "The message is {{ var1 }}"
        
