---
- hosts: all
  gather_facts: true
  tasks:
    - win_file:
        name: "C:\\Test_temp"
        state: directory
      register: file_name
    - debug:
        msg: Created
      when: file_name.failed == false
    - debug:
        msg: "Again Created"
      when: file_name.failed == "false"
    - debug:
        msg: "Again Created"
      when: file_name.failed == "False"
    - debug:
        msg: "Not Created"
      when: file_name.failed == true
    - debug:
        msg: "{{ ansible_hostname }} is the localhost"
    - set_stats:
        data:
          Token: "token1234"
          next_var: "Sophos Installation has started"
    - set_fact:
        data1: 0
    - debug:
         msg: "Not Matched"
      when: not data1 == 1
    - set_fact:
        data1: 2
    - debug:
        msg: "Matched"
      when: data1 == 2
