---
- hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: "{{ ansible_hostname }} is the localhost"
    - set_stats:
        data:
          Token: "token1234"
          next_var: "Sophos Installation has started"
    - set_fact:
        data1: 1
    - debug:
         msg: "Matched"
      when: data1 == "1"
