---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: "Create a new host"
      uri:
        url: "http://10.128.0.11/api/v2/inventories"
        method: GET
        url_username: admin
        url_password: password
        body_format: json
        validate_certs: false
        force_basic_auth: true
        return_content: yes
        status_code: 200
      register: this
    - name: "Start the block"
      block:
        - name: "Name of Inv"
          set_fact:
            inv_id: "{{ this.json.results[{{ item | int }}].id }}"
          when: this.json.results[item | int].name == "Windows"
          with_sequence: end=3
      when: this.json.results | count  > 0
        
