---
- hosts: "{{ serverIP }}"
  gather_facts: false
  tasks:
    - name: "Fetch | hostname"
      shell: cat /etc/hostname
      register: host_name
    - name: "block | success"
      block:
        - debug:
            msg: success
      when: 1 == 1
     
    - name: "block | failed"
      block:
        - fail:
            msg: failed
      when: 2 != 1
