---
- hosts: "{{ serverIP }}"
  gather_facts: false
  tasks:
    - name: "Fetch | hostname"
      shell: cat /etc/hostname
      register: host_name
    - name: "block | success"
      block:
        - debug:
            msg: success
      when: "par" == "par"
     
    - name: "block | failed"
      block:
        - fail:
            msg: failed
      when: "para" != "par"
      rescue:
        - debug:
            msg: "failed in block"
