---
# tasks file for role_import_playbook
- debug:
    msg: "Role has been triggered"
- name: "Create a dummy entry to store the servername/ip "
  add_host:
     name: TargetServerName
     server_ip: "{{ ansible_hostname }}"
- name: "Approve the Agent in the SCOM Management Server"
  import_playbook: test.yml
