---
# tasks file for role_calling_another_yml
- name: "call"
  debug:
    msg: "call another yaml file"
- name: "Include"
  include_tasks: installsp.yml
  
- name: "Import"
  import_playbook: new_server.yml
  vars:
    another_server: "10.128.0.12"
