---
# tasks file for role_rename_disk_drives
- name: "Check for a Rename Drives Temp directory"
  win_stat:
    path: "{{ rename_disks_temp_dir }}"
  register: temp_dir_result

- name: "Delete the Rename Drives temp directory if present"
  win_file:
    path: "{{ rename_disks_temp_dir }}"
    state: absent
  ignore_errors: true
  register: delete_status
  when: temp_dir_result.stat.exists == true
- debug:
    var: delete_status
- name: "Create a Rename Drives temp directory for copying the json content"
  win_file:
    path: "{{ rename_disks_temp_dir }}"
    state: directory
  ignore_errors: true
  register: dir_creation_result
- debug:
    var: dir_creation_result
    
- name: "get the ie version"
  win_shell: |
       $ie_version = (Get-Item 'C:\Program Files\Internet Explorer\iexplore.exe').VersionInfo.ProductVersion
       if($ie_version -ge "11.11.9600.16384")
       {
         Write-Host $true
       }
       else
       {
         $false
       }
  register: ie_version
- debug:
    var: ie_version
- debug:
    msg: "It's true"
  when: ie_version.stdout_lines[0] == "True"
  
  
- debug:
    msg: "It's false"
  when: ie_version.stdout_lines[0] == "False"
